### ISSUE TITLE
Update $AWS api calls to have intuitive properties

### ISSUE THREAD

**Issue by sam-goodwin** [functionless/functionless#241]
Based on feedback, mirroring the AWS sdk api exactly is not intuitive when the type of a name/arm is changed to be a reference to a Construct. 

Example:
```ts
$AWS.DynamoDB.GetItem({
  // more intuitive as "Table"
  TableName: table
});
```

**Comment by volkanunsal** [comment]
I also want to add that the return type of $AWS calls can be more intuitive as well. The DynamoDB expression attributes force the user to erase the type and recreate it in order to discriminate between type variants.

**Comment by thantos** [comment]
Do you have an example of your use case?

**Comment by volkanunsal** [comment]
Given a table such as `Table<SomeUnionType, any>`, and `SomeUnionType` being defined as 

```ts
type SomeUnionType = Type1 | Type2;
type Type1 = { type: 'a', property1: string };
type Type2 = { type: 'b', property2: string };
```

When I get an item of type `SomeUnionType` using 

```ts
$AWS.DynamoDB.GetItem({
  TableName: table
});
```

And when I inspect the property `type` in order to refine it to `type === 'a'`, Typescript should be able to tell that the object also includes `property1`. This is normally the case, but since the return type includes entity attributes of DynamoDB, that doesn't work:

```
const res = {
  type: { S: 'a' },
  property1: { S: 'value' }
}

if(res.type.S === 'a') {
   // type error here
   res.property1
}
```

Let me know if that makes send.

**Comment by sam-goodwin** [comment]
@volkanunsal  that does make sense. I'm surprised that is not working properly. Will look into it, but tracked in a separate issue as I'll be closing this one soon. https://github.com/functionless/functionless/issues/288
