### ISSUE TITLE
Step Functions filter using a Map Task

### ISSUE THREAD

**Issue by sam-goodwin** [functionless/functionless#57]
When filtering lists, e.g. `list.filter(..)`, we currently only support cases where the filter expression can be converted to JSON Path. We need to add support for using a Map Task which can call APIs, make Choices, etc.

Ex.
```ts
list.filter(item => {
  if(task(item)) {
    return false;
  } else {
    return true;
  }
})
```

**Comment by thantos** [comment]
I think the missing feature here is dynamic Array manipulation. 

* Build static array using States.Array allows a static array to be built
* tail recursion can iterate an array

Missing:
* Array concat
* Array append
* Dynamic array index access

We can tail an array to iterate an arbitrary sized array
* arr = realArray // create temp array
* arr[0] // access first
* arr = arr[1:] // update the temp array

But we cannot use the mechanism to filter because we cannot update the tail position
* kept = 0
* arr = realArray // create temp array
* arr[kept] // access next position - dynamic index is not supported
* if(predicate) kept++ // arithmetic is not supported
* arr = arr[kept+1:] // update the temp array - arithmetic and dynamic index are not supported

## Ideas

### 1 - Nested Arrays

Explore using nested arrays which can be created using `States.array(item, tail)`.

### 2 - String Manipulation

Array concat/append is not supported, however, SFN supports serialization and string formatting.

* Given an array of size N
* Map over the array, writing out a tuple of the predicate result (Pi) and value (Vi) for each value (i) in N
  * `out[i] = [Pi, Vi]`
* create a new string at str = `[`
* for each element in out (o)
  * `So = States.JsonToString(Vo)`
  * Concat `str` with So `States.Format('{},{}', $.str, $.So)`
* Rehydrate the array using `States.StringToJson`
  * `final = States.StringToJson($str)`

in typescript

```ts
const arr = someArray;
const predicateArray = arr.map(item => [predicate(item), JSON.stringify(item)]);
const str = predicateArray.filter(([keep]) => keep).reduce((str, [,itemStr]) => `${str},${itemStr}`, "[") + ];
return JSON.parse(str);
```
